UserManagementDemo.Web/Areas/Accounts/Controllers/ProfilesController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using UserManagementDemo.Domain.Models.Entities;
using UserManagementDemo.Service.Client.Actions.Commands;
using UserManagementDemo.Service.Client.Actions.Queries;
using UserManagementDemo.Service.Client.Interfaces;
using UserManagementDemo.Web.Areas.Accounts.Models;
using UserManagementDemo.Web.Controllers;

namespace UserManagementDemo.Web.Areas.Accounts.Controllers
{
    [Area("Accounts")]
    public class ProfilesController : RootController<ProfilesController>
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOnlineProfileService _profileManager;

        public ProfilesController(UserManager<ApplicationUser> userManager,
            IOnlineProfileService profileManager)
        {
            _userManager = userManager;
            _profileManager = profileManager;
        }

        [HttpGet]
        public async Task<IActionResult> SaveProfile(string profileId = null)
        {
            var onlineUser = await _userManager.GetUserAsync(User);
            var onlineProfile = _profileManager.SetOnlineProfile(onlineUser);

            if (profileId != null) 
            {
                var existingProfile = await _mediator.Send(
                    new GetOnlineProfileQuery()
                    {
                        Id = profileId,
                        EmailAddress = onlineProfile.EmailAddress
                    }
                );

                if (existingProfile.IsSuccessful)
                {
                    var userProfile = _mapper.Map<OnlineProfile>(existingProfile.ApiResponse);
                    var existingModel = new UserProfileViewModel
                    {
                        OnlineUser = onlineUser,
                        OnlineProfile = userProfile
                    };

                    return View(existingModel);
                }
            }
            else
            {
                var profileModel = new UserProfileViewModel
                {
                    OnlineUser = onlineUser,
                    OnlineProfile = onlineProfile
                };

                return View(profileModel);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SaveProfile(string profileId,
            UserProfileViewModel profileModel, string returnUrl = null)
        {
            var currentProfile = await _profileManager.GetByIdAsync(profileId);
            var onlineProfile = profileModel.OnlineProfile;

            returnUrl ??= Url.Content("~/");

            if (ModelState.IsValid)
            {
                if (profileId != null)
                {
                    onlineProfile.Id = profileId;

                    if (Request.Form.Files.Count > 0)
                    {
                        await ChangeProfilePicture(onlineProfile);
                    }
                    else
                    {
                        onlineProfile.Picture = currentProfile.Picture;
                    }

                    var updateProfile = _mapper.Map<UpdateProfileCommand>(onlineProfile);
                    await _mediator.Send(updateProfile);

                    return LocalRedirect(returnUrl);
                }
                else
                {
                    if (Request.Form.Files.Count > 0)
                    {
                        await ChangeProfilePicture(onlineProfile);
                    }

                    var createProfile = _mapper.Map<CreateProfileCommand>(onlineProfile);
                    await _mediator.Send(createProfile);

                    return LocalRedirect(returnUrl);
                }
            }

            return View(profileModel);
        }

        private async Task<byte[]> ChangeProfilePicture(OnlineProfile profile)
        {
            if (Request.Form.Files.Count > 0)
            {
                IFormFile picture = Request.Form.Files.FirstOrDefault();

                using (var dataStream = new MemoryStream())
                {
                    await picture.CopyToAsync(dataStream);
                    profile.Picture = dataStream.ToArray();
                }
            }

            return default;
        }
    }
}

UserManagementDemo.Web/Areas/Users/Controllers/VerifyController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using UserManagementDemo.Domain.Models.DTOs;
using UserManagementDemo.Domain.Models.Entities;
using UserManagementDemo.Service.Client.Interfaces;
using UserManagementDemo.Web.Controllers;

namespace UserManagementDemo.Web.Areas.Users.Controllers
{
    [Area("Users")]
    public class VerifyController : RootController<VerifyController>
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAuthenticateService _authenticateManager;
        private readonly IOnlineUserService _onlineUserManager;

        public VerifyController(UserManager<ApplicationUser> userManager,
            IAuthenticateService authenticateManager, IOnlineUserService onlineUserManager)
        {
            _userManager = userManager;
            _authenticateManager = authenticateManager;
            _onlineUserManager = onlineUserManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> TwoFactorVerification()
        {
            var userAccount = await _userManager.GetUserAsync(User);
            var userEmail = await _userManager.GetEmailAsync(userAccount);

            if (userAccount != null)
            {
                var userToken = await _authenticateManager.GetAuthKeyAsync(userAccount);
                var userQrCode = _authenticateManager.GenerateQRCodeUri(userEmail, userToken);

                var secureUser = new ProtectUserDto
                {
                    Token = userToken,
                    QRCode = userQrCode
                };
                
                return View(secureUser);
            }

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> TwoFactorVerification(ProtectUserDto secureAccess, string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            var userAccount = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                var tokenProvider = _userManager.Options.Tokens.AuthenticatorTokenProvider;
                var verificationCode = secureAccess.Code.Replace(" ", string.Empty);

                var validToken = await _userManager.VerifyTwoFactorTokenAsync(
                    userAccount, tokenProvider, verificationCode);

                if (validToken)
                {
                    await _userManager.SetTwoFactorEnabledAsync(userAccount, true);

                    _notificationService.SuccessMessage(
                        "You have successfully enabled 2FA in your account");

                    return LocalRedirect(returnUrl);
                }
            }

            return View(secureAccess);
        }

        [HttpGet]
        [Authorize]
        public IActionResult VerifyContactNumber()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> VerifyContactNumber(
            VerifyUserDto requestUser, string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");
            var currentUser =  await _userManager.GetUserAsync(User);

            if (ModelState.IsValid) 
            {
                if (currentUser != null)
                {
                    var changeContact = await _onlineUserManager.ChangeContactInfo(
                        currentUser, requestUser);

                    if (!changeContact.Succeeded)
                    {
                        _notificationService.ErrorMessage(
                            "There is an error trying to change your contact number");

                        return View();
                    }

                    _notificationService.SuccessMessage(
                        "Your contact number has been changed");

                    return LocalRedirect(returnUrl);
                }
            }

            return View(requestUser);
        }
    }
}

UserManagementDemo.Web/Areas/Accounts/Views/Profiles/SaveProfile.cshtml
@using Microsoft.AspNetCore.Identity;

@using UserManagementDemo.Domain.Models.Entities;
@using UserManagementDemo.Web.Areas.Accounts.Models;
@using UserManagementDemo.Web.Views.Shared.Components.Avatar
@using UserManagementDemo.Web.Views.Shared.Components.RecoveryCodes;
@using UserManagementDemo.Web.Views.Shared.Components.RecoveryCount;

@inject UserManager<ApplicationUser> UserManager
@model UserProfileViewModel

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-xl-3">
            <div class="card avatar-card">
                <div class="card-body p-4">
                    <div class="text-center">
                        <div class="avatar-profile mx-auto">
                            <partial name="_UserProfilePicture" model="Model" />
                            <div class="p-0 profile-image">
                                <input type="file" asp-for="OnlineProfile.Picture"
                                        class="form-control" style="display:none;" onchange="document.getElementById('switchPhoto').src = window.URL.createObjectURL(this.files[0])" />

                                <label asp-for="OnlineProfile.Picture" style="top: -20px" class="position-relative">
                                    <span class="rounded-circle bg-light text-body change-photo-icon">
                                        <i style="font-size: 1.5rem;" class="ri-camera-fill"></i>
                                    </span>
                                </label>
                                <span asp-validation-for="OnlineProfile.Picture" class="text-danger"></span>
                            </div>
                        </div>
                        <h5 class="text-medium mb-1">
                            @UserManager.GetUserAsync(User).Result.FirstName
                            @UserManager.GetUserAsync(User).Result.LastName
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="col-xl-9">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs-custom rounded card-header-tabs border-bottom-0" role="tablist">
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active" href="#info" data-toggle="tab" role="tab" aria-selected="true">
                                Profile Info
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#settings" data-toggle="tab" role="tab" aria-selected="false">
                                Profile Settings
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="card-body p-4">
                    <div class="tab-content">
                        <div class="tab-pane" id="settings" role="tabpanel">
                            <div class="pb-2">
                                @(await Component.InvokeAsync<RecoveryCountViewComponent>())

                                @if (Model.OnlineUser.PhoneNumber == null)
                                {
                                    <div class="d-flex flex-column flex-sm-row mb-4 mb-sm-0 mt-2">
                                        <div class="flex-grow-1">
                                            <h6 class="mb-1">PhoneNumber Verification</h6>
                                            <p class="text-muted">
                                                A Contact number is needed to verify your Identity and can be used to recover
                                                your account if you forget your email or password credentials.
                                            </p>
                                        </div>
                                        <div class="flex-shrink-0 m-sm-3">
                                            <a asp-area="Users" asp-controller="Verify" asp-action="VerifyContactNumber" 
                                                class="btn btn-sm btn-primary text-light">
                                                Add Contact Number
                                            </a>
                                        </div>
                                    </div>
                                }
                                @if (UserManager.GetTwoFactorEnabledAsync(Model.OnlineUser).Result.Equals(false))
                                {
                                    <div class="d-flex flex-column flex-sm-row mb-4 mb-sm-0 mt-2">
                                        <div class="flex-grow-1">
                                            <h6 class="mb-1">Enable 2FA Authentication</h6>
                                            <p class="text-muted">
                                                Protect your account from intrusion by using a secure Passcode generator
                                                or QR Code sent to your personal or work device.
                                            </p>
                                        </div>
                                        <div class="flex-shrink-0 m-sm-3">
                                            <a asp-area="Users" asp-controller="Verify" asp-action="TwoFactorVerification"
                                                class="btn btn-sm btn-primary text-light">
                                                Setup OTP Authentication
                                            </a>
                                        </div>
                                    </div>
                                }
                                @if (UserManager.CountRecoveryCodesAsync(Model.OnlineUser).Result == 0)
                                {
                                    <div class="d-flex flex-column flex-sm-row mb-sm-0 mt-2">
                                        <div class="flex-grow-1">
                                            <h6 class="mb-1">Account Recovery Codes</h6>
                                            <p class="text-muted">
                                                Restore access to your account in case you have lost your
                                                Authenticator device by using a list of recovery codes
                                            </p>
                                        </div>
                                        <div class="flex-shrink-0 m-sm-3">
                                            <a href="#recoveryCodes" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="recoveryCodes"
                                               class="btn btn-sm btn-primary text-light">
                                                Show Recovery Codes
                                            </a>
                                        </div>
                                    </div>
                                }
                                <div class="collapse" id="recoveryCodes">
                                    <div class="card card-body">
                                        @(await Component.InvokeAsync<RecoveryCodesViewComponent>())
                                    </div>
                                </div>

                            </div>
                        </div>          

                        <div class="tab-pane show active" id="info" role="tabpanel">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="mb-3">
                                        <label asp-for="OnlineUser.FirstName" class="form-label"></label>
                                        <input asp-for="OnlineUser.FirstName" type="text" class="form-control" readonly />
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.MiddleName" class="form-label"></label>
                                        <input asp-for="OnlineProfile.MiddleName" type="text" class="form-control" />
                                        <span asp-validation-for="OnlineProfile.MiddleName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="mb-3">
                                        <label asp-for="OnlineUser.LastName" class="form-label"></label>
                                        <input asp-for="OnlineUser.LastName" type="text" class="form-control" readonly />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.EmailAddress" class="form-label"></label>
                                        <input asp-for="OnlineProfile.EmailAddress" type="email" class="form-control" readonly />
                                    </div>
                                </div>
                                @if (Model.OnlineUser.PhoneNumber != null)
                                {
                                    <div class="col-lg-6">
                                        <div class="mb-3">
                                            <label asp-for="OnlineUser.PhoneNumber" class="form-label"></label>
                                            <input asp-for="OnlineUser.PhoneNumber" type="text" class="form-control" readonly />
                                        </div>
                                    </div>
                                }
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.DayOfBirth" class="form-label"></label>
                                        <input asp-for="OnlineProfile.DayOfBirth" type="date" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.Occupation" class="form-label"></label>
                                        <input asp-for="OnlineProfile.Occupation" type="text" class="form-control" />
                                        <span asp-validation-for="OnlineProfile.Occupation" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.Website" class="form-label"></label>
                                        <input asp-for="OnlineProfile.Website" type="text" class="form-control" />
                                        <span asp-validation-for="OnlineProfile.Website" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.Location" class="form-label"></label>
                                        <input asp-for="OnlineProfile.Location" type="text" class="form-control" />
                                        <span asp-validation-for="OnlineProfile.Location" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="mb-3">
                                        <label asp-for="OnlineProfile.Language" class="form-label"></label>
                                        <input asp-for="OnlineProfile.Language" type="text" class="form-control" />
                                        <span asp-validation-for="OnlineProfile.Language" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                    <a asp-area="Dashboard" asp-controller="Home" asp-action="Index" type="button" class="btn">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>